### ISSUE TITLE
Why is this generator this minimal?

### ISSUE THREAD

**Issue by ghost** [h5bp/generator-h5bp#17]
I like having a generator that just scaffolds h5bp for me, but some ideas:
- [ ] I don't want jQuery on all my projects. Why don't we have an option to get it out?
- [ ] `.htaccess`. Why not make it an option (list) to choose other configs?
- [ ] When I making simple sites, I don't want all magic inside `main.css`. Why not to make it optional?
- [ ] Sometimes I don't want to use Google analytics, so the first thing I always need to do is change that snippet with my own. Why? 
- [ ] I always have to get rid of Modernizr after running `yo h5bp`. why oh why?
- [ ] Some days I don't use git? Why do we have a gitignore then? Make it optional, guys.

Yeoman provides all this power, why not to use it @sindresorhus?

**Comment by sindresorhus** [comment]
PR welcome for more prompt questions.

I just wasn't sure what to prompt when I made it as I don't use H5BP much.

**Comment by supergray** [comment]
Open for 22 days and nothing happened :(

**Comment by arthurvr** [comment]
I'm all :+1: for this idea.

> Why not make it an option (list) to choose other configs?

Using yeoman's composability and `generator-server-configs` that sounds like pretty easy isn't it?
