### ISSUE TITLE
Bump H5BP version to 5.1.0

### ISSUE THREAD

**Issue by joejoinerr** [h5bp/generator-h5bp#18]

**Comment by arthurvr** [comment]
Sure. Thanks for letting us know.

**Comment by arthurvr** [comment]
And @alrra was just a second quicker than I :) Thanks @alrra.

**Comment by alrra** [comment]
Thanks @joejoinerr! Updated in 93ea8336999ef9315d856da662c7fe7f394abd66.

--

Waiting for @sindresorhus to push on `npm`.
