### ISSUE TITLE
Suggestion about server config file.

### ISSUE THREAD

**Issue by drKraken** [h5bp/generator-h5bp#20]
Suggest to add ability for choosing which server config file user want to include.
Make it as a question in prompt... Is it make sense for you?
@sindresorhus @arthurvr

**Comment by sindresorhus** [comment]
That's what https://github.com/h5bp/generator-server-configs is for.

**Comment by drKraken** [comment]
sure, but i think it's good to have the possibility of choice in this generator too.

**Comment by sindresorhus** [comment]
Nah, you can easily run the server config generator afterwards. Most users of this generator won't need it, so I don't think it's worth adding the extra prompt. Thanks for the suggestion though. Would be happy to get other suggestions on how we can improve this generator :)
